### PR TITLE
cleanup footer

### PR DESCRIPTION
**Pull request by joeromine**

### CODE REVIEW

**Comment by stephanlamoureux** [comment]
this looks behind main, doesn't have the footer on it.

**Review by stephanlamoureux — CHANGES_REQUESTED** [review]
Looks like it's a little behind main, there is no footer in this one. 

edit: nevermind, helps if I pull the new changes to your branch!

**Review by stephanlamoureux — APPROVED** [review]

**Comment by stephanlamoureux** [comment]
Maybe just add a little spacing between the "coded by" part and the GitHub links?

**Review by stephanlamoureux — CHANGES_REQUESTED** [review]
It looks good but it breaks the footer when the page is re-sized now, will have to update the media queries.

**Comment by joeromine** [comment]
Will put more work into it and push again

**Pull request closed without merging**
