### PR TITLE
added basic navbar

### PR DESCRIPTION
**Pull request by stephanlamoureux**
Need to get rid of the margin around the nav

### CODE REVIEW

**Comment by dtetreau251** [comment]
is the moon supposed to have a hover?

**Comment by stephanlamoureux** [comment]
> is the moon supposed to have a hover?

No, I just had to go to bed 😴 didn’t fully finish it

**Comment by stephanlamoureux** [comment]
Here is what is left:
- Remove the margin or border that is around the nav from the default bootstrap styling
- Remove hover on the moon icon
- Add link names, styling and href
- Add donate button

**Review by joeromine — CHANGES_REQUESTED** [review]
Please use vwc font and update links to the actual names and hrefs

**Review by joeromine — APPROVED** [review]

**Pull request merged**
