### PR TITLE
changed donate color to match vwc and added hover

### PR DESCRIPTION
**Pull request by stephanlamoureux**
#278

### CODE REVIEW

**Review by joeromine — CHANGES_REQUESTED** [review]
The blue button change needs to be tied into the dark/light theme

**Review by joeromine — CHANGES_REQUESTED** [review]
Please do the same for the other two buttons.

**Comment by stephanlamoureux** [comment]
added color change to dark mode

**Comment by stephanlamoureux** [comment]
changed the other two buttons

**Review by joeromine — APPROVED** [review]

**Comment by stephanlamoureux** [comment]
fixes #288 as well, moon border.

**Pull request merged**
