### PR TITLE
Event listener should be all up to date.

### PR DESCRIPTION
**Pull request by mario-mitchell**

### CODE REVIEW

**Review by dtetreau251 — COMMENTED** [review]
look good to me!

@joeromine just needs to approve

**update** See comment below

**Comment by dtetreau251** [comment]
somehow the range input is a number again. I'll fix it with my next PR but I included work on the form anyways

**Review by joeromine — CHANGES_REQUESTED** [review]
Let's change the event listener to fire on submit and not click.

**Comment by mario-mitchell** [comment]
> look good to me!
> 
> @joeromine just needs to approve
> 
> I looked at his branch on my machine earlier and it was behind but I may not have rebased. May want to check. I didn't see the footer and the range input was a number.

I see the footer in my VS code @dtetreau251.

**Comment by mario-mitchell** [comment]
> Let's change the event listener to fire on submit and not click.

@joeromine done.

**Comment by dtetreau251** [comment]
> > look good to me!
> > @joeromine just needs to approve
> > I looked at his branch on my machine earlier and it was behind but I may not have rebased. May want to check. I didn't see the footer and the range input was a number.
> 
> I see the footer in my VS code @dtetreau251.

I still had the old version of your branch in my machine because you deleted it and did a new pR. It wasn't pulling the new one even if I rebased. iI had to delete the old one with the same name and then I could see the new one. It was werid

**Comment by mario-mitchell** [comment]
@joeromine changes made.

**Review by joeromine — APPROVED** [review]

**Pull request merged**
