### PR TITLE
Changed from bootstrap to just css

### PR DESCRIPTION
**Pull request by HerndonC**
Completely revamped the grid from bootstrap to just regular css. 
Changed the layout to be cleaner and have the border and bookmark have the same colors.
Added functionality to the bookmark. 
Added a lot of css so we can change every aspect of it in the future a lot more easily.

### CODE REVIEW

**Review by dtetreau251 — COMMENTED** [review]
Much better! Looks great!

**Review by joeromine — CHANGES_REQUESTED** [review]
Please test in light and dark mode. Also, how do I get to the job posting and what does 'BookMark This Page' do?

**Review by joeromine — CHANGES_REQUESTED** [review]
image

let's have the border match the background

**Review by joeromine — CHANGES_REQUESTED** [review]
Please check the responsiveness 375x812 iPhone X

**Comment by dtetreau251** [comment]
@joeromine changes made. Please review

**Comment by dtetreau251** [comment]
made cards from the grid. removed  the grid and made the cards block display. Dark mode needs work.

**Review by joeromine — APPROVED** [review]

**Pull request merged**
