### PR TITLE
just added a stylefolder

### PR DESCRIPTION
**Pull request by mario-mitchell**

### CODE REVIEW

**Review by joeromine — CHANGES_REQUESTED** [review]
Mario, please put the js file in a folder. Same with css and update the related tags.

ty

**Comment by mario-mitchell** [comment]
@joeromine should be good to go.  added the folders.

**Review by joeromine — CHANGES_REQUESTED** [review]
Please update the href in the link tag for the new folder. Also, we need a script tag for the new js file.

**Comment by mario-mitchell** [comment]
@joeromine Updated the folders and tags. the script tag is at the bottom of the body.

**Review by joeromine — CHANGES_REQUESTED** [review]
Mario, please move the script tag to the bottom of body.

Looking good!

Joe

**Comment by mario-mitchell** [comment]
@joeromine  done. thought it was at the bottom, missed the footer.

**Review by joeromine — APPROVED** [review]
Looks good!

**Pull request merged**
