### PR TITLE
fixed duplicate range and search.

### PR DESCRIPTION
**Pull request by HerndonC**

### CODE REVIEW

**Comment by stephanlamoureux** [comment]
Can you remove the duplicate :root CSS too?

**Comment by HerndonC** [comment]
> Can you remove the duplicate :root CSS too?

Yea, that and also I think the zipcode is there, I'll try to fix those in a few moments. Gotta take care of something first.

**Comment by HerndonC** [comment]
> Can you remove the duplicate :root CSS too?

Since the only file here is the index, that would have to be put in issues.

**Comment by dtetreau251** [comment]
I think I fixed your merge conflict.

**Comment by HerndonC** [comment]
> I think I fixed your merge conflict.

I hope so, anything else I see I can try to fix.

**Pull request merged**
